## NUMPY

In [1]:
import numpy as np

In [6]:
a = np.array([1, 2, 3, 4, 5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
[[1, 2, 3, 4],
 [5, 6, 7, 8],
 [9, 10, 11, 12]]

In [9]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)
print(a.ndim)
print(a.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
(3, 4)


In [12]:
a[1][2]

7

In [13]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [21]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [22]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [26]:
np.empty((2,2))

array([[1., 1.],
       [1., 1.]])

In [28]:
list(range(5))

[0, 1, 2, 3, 4]

In [31]:
np.arange(2, 10, 2)

array([2, 4, 6, 8])

In [64]:
a_list = list(range(10))
a_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [33]:
a_list.append(list(range(3)))

In [34]:
a_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, [0, 1, 2]]

In [65]:
for i in range(3):
    a_list.append(i)

print(a_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2]


In [66]:
np.append(range(10), range(3))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2])

In [36]:
a_numpy = np.arange(10)
a_numpy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
np.arange(6).reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [39]:
np.append(a_numpy, range(3))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2])

In [46]:
np.append(a_numpy, np.arange(6).reshape(3,2))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5])

In [48]:
np.append([[1, 2, 3], [4, 5, 6]], [[7, 8, 9]], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
np.append([[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [7, 8, 9]], axis=1)

array([[1, 2, 3, 7, 8, 9],
       [4, 5, 6, 7, 8, 9]])

In [51]:
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
np.array([7, 8, 9])

array([7, 8, 9])

In [58]:
np.append([[1, 2, 3], [4, 5, 6]], [[7, 8, 9, 10]])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
axis=0 baris
axis=1 kolom

In [73]:
np.delete(a, -1, axis=0)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [75]:
b_sort = np.append(range(52,55), range(21,27))

In [77]:
np.sort(b_sort)

array([21, 22, 23, 24, 25, 26, 52, 53, 54])

In [82]:
print(a)
print(a.shape)
print(a.ndim)
print(a.size)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
2
12


In [92]:
a.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [94]:
np.arange(15).reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [102]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [ ]:
[:, newaxis]

In [110]:
a[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [111]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', '

In [112]:
a

array([0, 1, 2, 3, 4])

In [116]:
np.expand_dims(a, axis=1).shape

(5, 1)

#### Indexing Slicing

In [117]:
a = np.array([0,1,2,3,4,5])
a

array([0, 1, 2, 3, 4, 5])

In [118]:
a[0]

0

In [119]:
a[0:3]

array([0, 1, 2])

In [120]:
a[:3]

array([0, 1, 2])

In [121]:
a[:]

array([0, 1, 2, 3, 4, 5])

In [122]:
a[-3:]

array([3, 4, 5])

In [123]:
a[:-1]

array([0, 1, 2, 3, 4])

In [125]:
a > 2

array([False, False, False,  True,  True,  True])

In [130]:
a[np.array([False, False, True,  True, False,   True])]

array([2, 3, 5])

In [132]:
a[a > 2]

array([3, 4, 5])

In [134]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [137]:
a[a>5]

array([ 6,  7,  8,  9, 10, 11])

In [140]:
above_five = a > 8

In [141]:
a[above_five]

array([ 9, 10, 11])

In [ ]:
True False

In [ ]:
==
>=
<=
>
<

In [147]:
a * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [146]:
a_list * 2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2]

In [150]:
a[a % 2 == 0]

array([ 0,  2,  4,  6,  8, 10])

In [151]:
genap = a % 2 == 0

a[genap]


array([ 0,  2,  4,  6,  8, 10])

In [153]:
a[(a > 2) & (a < 11) & (a % 2 != 0)]

array([3, 5, 7, 9])

In [155]:
arr = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [163]:
a_1 = np.append([[1, 1]], [[2, 2]], axis=0)

array([[1, 1],
       [2, 2]])

In [164]:
a_1 = np.array([[1, 1],
                [2, 2]])
a_2 = np.array([[3, 3],
                [4, 4]])

In [167]:
np.append(a_1, a_2, axis=0)

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [168]:
np.append(a_1, a_2, axis=1)

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [171]:
np.vstack([a_1, a_2])  # append axis 0

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [172]:
np.hstack([a_1, a_2])  # append axis 1

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [174]:
arrsplit = np.array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
     [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [179]:
np.arange(10, 100, 5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [184]:
tuple(range(10, 100, 5))

(10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95)

In [185]:
arrsplit

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [191]:
h_1, h_2, h_3 = np.hsplit(arrsplit, 3)

In [196]:
np.hstack([h_1, h_2, h_3])

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [192]:
h_1

array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]])

In [194]:
h_2

array([[ 5,  6,  7,  8],
       [17, 18, 19, 20]])

In [200]:
arrsplit.shape

(2, 12)

In [199]:
np.vsplit(arrsplit, 2)

[array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]),
 array([[13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])]

In [202]:
np.hsplit(arrsplit, 10)

ValueError: array split does not result in an equal division

In [207]:
b = a

In [208]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [211]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [213]:
b[1][-1] = 100

In [214]:
b

array([[  0,   1,   2,   3],
       [  4,   5,   6, 100],
       [  8,   9,  10,  11]])

In [215]:
a

array([[  0,   1,   2,   3],
       [  4,   5,   6, 100],
       [  8,   9,  10,  11]])

In [216]:
id(a)

140386237590928

In [217]:
id(b)

140386237590928

In [218]:
id(a) == id(b)

True

In [ ]:
object -> a -> b

In [223]:
print(id(a))
print(id(a.view()))

140386237590928
140386235821168


In [231]:
print(id(a))
print(id(a.view()))

140386237590928
140386235822992


In [233]:
c = a.view()

In [234]:
print(id(a))
print(id(c))

140386237590928
140386235823280


In [246]:
id(a.copy())

140386235824720

In [253]:
id(a)

140386237590928

In [ ]:
dataframe
backup_dataframe = dataframe.copy()

In [ ]:
dataframe = backup_dataframe.copy()

#### Basic Operations

In [ ]:
+
-
/
*
%

In [258]:
a

array([[  0,   1,   2,   3],
       [  4,   5,   6, 100],
       [  8,   9,  10,  11]])

In [255]:
a + 5

array([[  5,   6,   7,   8],
       [  9,  10,  11, 105],
       [ 13,  14,  15,  16]])

In [256]:
a - 5

array([[-5, -4, -3, -2],
       [-1,  0,  1, 95],
       [ 3,  4,  5,  6]])

In [257]:
a * 3

array([[  0,   3,   6,   9],
       [ 12,  15,  18, 300],
       [ 24,  27,  30,  33]])

In [259]:
a / 3

array([[ 0.        ,  0.33333333,  0.66666667,  1.        ],
       [ 1.33333333,  1.66666667,  2.        , 33.33333333],
       [ 2.66666667,  3.        ,  3.33333333,  3.66666667]])

In [261]:
a % 3

array([[0, 1, 2, 0],
       [1, 2, 0, 1],
       [2, 0, 1, 2]])

In [262]:
a + 5 - 7 * 3

array([[-16, -15, -14, -13],
       [-12, -11, -10,  84],
       [ -8,  -7,  -6,  -5]])

In [263]:
a + a

array([[  0,   2,   4,   6],
       [  8,  10,  12, 200],
       [ 16,  18,  20,  22]])

In [272]:
a

array([[  0,   1,   2,   3],
       [  4,   5,   6, 100],
       [  8,   9,  10,  11]])

In [269]:
np.ones(12).reshape(3, 4)  * 3

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [274]:
a * np.ones(12).reshape(3, 4) * 3

array([[  0.,   3.,   6.,   9.],
       [ 12.,  15.,  18., 300.],
       [ 24.,  27.,  30.,  33.]])

In [ ]:
a b    x    a  b
c d         c  d

In [ ]:
a*a + b*c        a*b + b*d
c*a + d*c        c*b + d*d

In [ ]:
np.dot

In [281]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [282]:
np.arange(5).sum()

10

In [284]:
np.sum(np.arange(5))

10

In [288]:
a.sum()  # method call

159

In [289]:
np.sum(a)  # function call

159

In [290]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__git_version__',
 '__loader__',

In [291]:
np.nan

nan

In [ ]:
not a number

In [ ]:
null

In [ ]:
np.sum()
np.absolute()
np.mean()
np.median()
np.add()
np.subtract()
np.nansum()

In [301]:
np.array([np.nan, 5]).sum()

nan

In [302]:
np.nansum(np.array([np.nan, 5]))

5.0

In [309]:
np.linspace(1, 4, num=4).reshape(2, 2)

array([[1., 2.],
       [3., 4.]])

In [306]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [310]:
np.linspace(1, 4, num=4).reshape(2, 2).dot(np.identity(2))

array([[1., 2.],
       [3., 4.]])

In [312]:
b = np.array([[1, 1], [2, 2]])
b

array([[1, 1],
       [2, 2]])

In [315]:
b.sum(axis=1)

array([2, 4])

In [325]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [322]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [331]:
x1 = np.linspace(5, 122, num=4).reshape(2, 2)
x2 = np.linspace(8, 32, num=4).reshape(2, 2)

In [332]:
x1

array([[  5.,  44.],
       [ 83., 122.]])

In [333]:
x2

array([[ 8., 16.],
       [24., 32.]])

In [334]:
x1 * x2

array([[  40.,  704.],
       [1992., 3904.]])

In [340]:
np.product([x1, x2], axis=1)

array([[ 415., 5368.],
       [ 192.,  512.]])

In [342]:
np.maximum(x1, x2)

array([[  8.,  44.],
       [ 83., 122.]])

In [343]:
np.minimum(x1, x2)

array([[ 5., 16.],
       [24., 32.]])

In [346]:
np.std([x1, x2], axis=0)

array([[ 1.5, 14. ],
       [29.5, 45. ]])

In [348]:
np.min(x2)

8.0

In [352]:
np.random.randint(1, 100, size=10)

array([17, 83, 54, 96, 23, 31, 20, 39, 14, 41])

In [354]:
a

array([[  0,   1,   2,   3],
       [  4,   5,   6, 100],
       [  8,   9,  10,  11]])

In [353]:
np.random.randn(3, 4)

array([[ 1.23927359,  0.46242861, -1.8134811 , -0.66283031],
       [ 1.65377742, -0.4346629 , -0.77841869,  0.77996902],
       [ 1.15629645,  0.68846936,  0.1640313 , -2.6664399 ]])

In [364]:
d = np.random.randn(4, 3)

In [365]:
a * d

ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [ ]:
(4,3)(3,4)

In [367]:
a

array([[  0,   1,   2,   3],
       [  4,   5,   6, 100],
       [  8,   9,  10,  11]])

In [368]:
d

array([[-1.3629784 ,  1.13092309,  0.63627312],
       [ 0.01766453, -0.26279328,  0.35527752],
       [-1.45468115,  1.6001775 , -1.5054766 ],
       [ 1.62902022,  1.26927194, -0.34215939]])

In [366]:
a @ d

array([[  1.99536289,   6.74537753,  -3.68215386],
       [148.81034421, 139.73798469, -38.92731889],
       [ -7.37243556,  36.6460115 , -10.53083672]])

In [371]:
d @ a

array([[  9.6138773 ,  10.01809511,  10.42231291, 116.00237835],
       [  1.79104704,   1.90119581,   2.01134457, -22.31828201],
       [ -5.64310281,  -7.00308306,  -8.36306331, 139.09346392],
       [  2.3398126 ,   4.89594537,   7.45207813, 128.05050107]])

In [369]:
a.dot(d)

array([[  1.99536289,   6.74537753,  -3.68215386],
       [148.81034421, 139.73798469, -38.92731889],
       [ -7.37243556,  36.6460115 , -10.53083672]])

In [370]:
np.dot(a, d)

array([[  1.99536289,   6.74537753,  -3.68215386],
       [148.81034421, 139.73798469, -38.92731889],
       [ -7.37243556,  36.6460115 , -10.53083672]])

In [387]:
d[1:3, 1]

array([-0.26279328,  1.6001775 ])

In [ ]:
d[baris, kolom]

In [388]:
d

array([[-1.3629784 ,  1.13092309,  0.63627312],
       [ 0.01766453, -0.26279328,  0.35527752],
       [-1.45468115,  1.6001775 , -1.5054766 ],
       [ 1.62902022,  1.26927194, -0.34215939]])

In [389]:
d[1:3, 0:2]

array([[ 0.01766453, -0.26279328],
       [-1.45468115,  1.6001775 ]])

In [390]:
d

array([[-1.3629784 ,  1.13092309,  0.63627312],
       [ 0.01766453, -0.26279328,  0.35527752],
       [-1.45468115,  1.6001775 , -1.5054766 ],
       [ 1.62902022,  1.26927194, -0.34215939]])

In [391]:
d.T

array([[-1.3629784 ,  0.01766453, -1.45468115,  1.62902022],
       [ 1.13092309, -0.26279328,  1.6001775 ,  1.26927194],
       [ 0.63627312,  0.35527752, -1.5054766 , -0.34215939]])

In [392]:
d.transpose()

array([[-1.3629784 ,  0.01766453, -1.45468115,  1.62902022],
       [ 1.13092309, -0.26279328,  1.6001775 ,  1.26927194],
       [ 0.63627312,  0.35527752, -1.5054766 , -0.34215939]])

In [393]:
np.transpose(d)

array([[-1.3629784 ,  0.01766453, -1.45468115,  1.62902022],
       [ 1.13092309, -0.26279328,  1.6001775 ,  1.26927194],
       [ 0.63627312,  0.35527752, -1.5054766 , -0.34215939]])

In [394]:
d.reshape(3, 4)

array([[-1.3629784 ,  1.13092309,  0.63627312,  0.01766453],
       [-0.26279328,  0.35527752, -1.45468115,  1.6001775 ],
       [-1.5054766 ,  1.62902022,  1.26927194, -0.34215939]])

In [395]:
ndarr = np.array([[[1, 2], [3, 4]],
                  [[5, 6], [7, 8]]])

print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [396]:
ndarr.ndim

3

In [397]:
ndarr.shape

(2, 2, 2)

In [398]:
ndarr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [400]:
ndarr.reshape(8)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [399]:
ndarr.flatten().reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
error = (1/n) * np.sum(np.square(observed - prediction))